import torch.nn as nn
import torch
from torch import optim
from models.Generator import Generator
from models.Discriminator import PatchDiscriminator
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

""" A class for combining the Generator and Discriminator models and train them alternately.

Attributes
----------
gen : <class nn.Module>
    The GAN's generator
disc : <class nn.Module>
    The GAN's discriminator
opt_G : <class optim.Adam>
    The optimizer for the Generator
opt_D : <class optim.Adam>
    The optimizer for the Discriminator

Methods
-------
optimize():
    Given the input and target data, performs one round of training on the generator and discriminator models
"""


def set_requires_grad(model, requires_grad=True):
    for p in model.parameters():
        p.requires_grad = requires_grad


class ColorizationGAN(nn.Module):
    """ Class initialization method. Initialize Generator, Discriminator, and optimizers.

    Arguments
    ----------
    lr_g : <class 'float'>
        the learning rate for the Generator parameters
    lr_d : <class 'float'>
        the learning rate for the Discriminator parameters
    beta1 : <class 'float'>
        the first beta parameter for the Adam optimizer
    beta2 : <class 'float'>
        the second beta parameter for the Adam optimizer
    lambda_l1: <class 'float'>
        the factor by which the L1 loss is scaled before adding it to the GAN's loss
    pretrained : <class 'bool'>
        boolean to control whether to generate a pretrained ResNet encoder or a U-Net encoder from scratch
    """

    def __init__(self, lr_g=0.0002, lr_d=0.0002, beta1=0.5, beta2=0.999, lambda_l1=100, pretrained=True):
        super().__init__()

        self.lambda_l1 = lambda_l1

        # Instantiate the Generator network
        self.gen = Generator(pretrained)
        self.gen = self.gen.to(device)
        # Instantiate the Discriminator network
        self.disc = PatchDiscriminator()
        self.disc = self.disc.to(device)

        # This will be replaced with the implementation of the gan loss
        self.GANloss = nn.Module
        self.L1Loss = nn.Module

        # Instantiate Adam optimizers
        self.opt_G = optim.Adam(self.net_G.parameters(), lr=lr_g, betas=(beta1, beta2))
        self.opt_D = optim.Adam(self.net_D.parameters(), lr=lr_d, betas=(beta1, beta2))

    def optimize(self, L, ab):
        """ Performs one round of training on a batch of images in the Lab colorspace.

        Arguments
        ----------
        L : <class 'Tensor'>
            the L channel of the image
        ab : <class 'Tensor'>
            the real ab channels of the image

        Returns
        -------
        loss_D : The loss for the discriminator (fake + real)
        loss_G : The loss for the generator (GANloss + L1)
        """

        L = L.to(device)
        ab = ab.to(device)

        # Get color channels from Generator
        fake_ab = self.net_G(L)
        self.disc.train()
        set_requires_grad(self.disc, True)
        self.disc.zero_grad()

        # Compose fake images and pass them to the Discriminator
        fake_image = torch.cat([L, fake_ab], dim=1)
        fake_preds = self.disc(fake_image.detach())
        loss_D_fake = self.GANloss(fake_preds, False)

        # Pass the real images to the Discriminator
        real_image = torch.cat([L, ab], dim=1)
        real_preds = self.disc(real_image)
        loss_D_real = self.GANloss(real_preds, True)

        # Combine losses and calculate the gradients
        loss_D = (loss_D_fake + loss_D_real) * 0.5
        loss_D.backward()

        # Update the Discriminator parameters
        self.opt_D.step()

        self.gen.train()
        self.set_requires_grad(self.disc, False)
        self.opt_G.zero_grad()

        # Combine the "reward signal" from the Discriminator with L1 loss
        fake_preds = self.net_D(fake_image)
        loss_G_GAN = self.GANloss(fake_preds, True)
        loss_G_L1 = self.L1Loss(fake_ab, ab) * self.lambda_L1
        loss_G = loss_G_GAN + loss_G_L1
        loss_G.backward()

        # Update the parameters of the Generator
        self.opt_G.step()

        return loss_D.item(), loss_G.item()

    def test(self, L, ab):
        """ Passes the input through the GAN in test mode.

        Arguments
        ----------
        L : <class 'Tensor'>
            the L channel of the image
        ab : <class 'Tensor'>
            the real ab channels of the image

        Returns
        -------
        loss_D : The loss for the Discriminator (fake + real)
        loss_G : The loss for the Generator (GANloss + L1)
        fake_image : The images generated by the GAN
        """

        L = L.to(device)
        ab = ab.to(device)

        # Get color channels from Generator
        fake_ab = self.net_G(L)

        self.gen.eval()
        self.disc.eval()

        with torch.no_grad:
            # Get color channels from Generator
            fake_ab = self.net_G(L)
            # Compose fake images and pass them to the Discriminator
            fake_image = torch.cat([L, fake_ab], dim=1)
            fake_preds = self.disc(fake_image.detach())
            loss_D_fake = self.GANloss(fake_preds, False)
            # Pass the real images to the Discriminator
            real_image = torch.cat([L, ab], dim=1)
            real_preds = self.disc(real_image)
            loss_D_real = self.GANloss(real_preds, True)
            # Combine losses and calculate the gradients
            loss_D = (loss_D_fake + loss_D_real) * 0.5

            # Combine the "reward signal" from the Discriminator with L1 loss
            fake_preds = self.net_D(fake_image)
            loss_G_GAN = self.GANloss(fake_preds, True)
            loss_G_L1 = self.L1Loss(fake_ab, ab) * self.lambda_L1
            loss_G = loss_G_GAN + loss_G_L1

        return loss_D.item(), loss_G.item(), fake_image

    def generate(self, L):
        """ Colorize black and white images, for cases where the real a and b channels are not present,
        -> the function you would use if you wanted to serve it in an application.

        Arguments
        ---------
        L : <class 'Tensor'>
            the L channel of the image

        Returns
        -------
        fake_image : The images generated by the GAN
        """

        L = L.to(device)
        self.gen.eval()
        # Get color channels from Generator
        fake_ab = self.net_G(L)
        # Compose fake images
        fake_image = torch.cat([L, fake_ab], dim=1)
        return fake_image